// Generated by https://quicktype.io

export interface DashboardSummaryResponse {
	paidOrders: number;
	notPaidOrders: number;
	numberOfClients: number;
	numberOfOrders: number;
	numberOfProducts: number;
	productsWithNoStock: number;
	lowInventory: number;
}
